Add CheckSpecies module
projectdissolve/dissolve pull request #366
Opened 2020-09-04 14:48 UTC by trisyoungs

This PR adds a new module, `CheckSpecies`, to properly assess the atom types and forcefield parameters present in a species, particularly those applied automatically from within Dissolve.

Work includes:
- Addition of new keywords `IntegerStringVectorKeyword` and `IntegerDoubleVectorKeyword` allowing general input of a set number of integers (in this instance, atom indices) followed by a variable list of strings or doubles. The underlying information is stored in a `std::vector` of `std::tuple`, with the tuple containing further `std::vector`s of the integer and string/double data.
- Updating atom type names in the OPLS-AA forcefield, some of which were using asterisks that were interpreted as wildcards when in fact they are purely identifiers.
- Updating the NETA system test to thoroughly check applied atom types and terms from the automatic typing routines, rather than just assume that the successful application of terms means the correct application of terms.

Notes:
- The new keyword classes could be template-driven, but as they are relatively short and would require specialisations this was not performed.

2020-09-09 12:44 UTC, DanNixon requested changes
Looks good :+1: and nice to see some more testing, just some minor comments.

2020-09-09 12:44 UTC, DanNixon commented on src/modules/checkspecies/functions.cpp
> +    if (source.size() != ref.size())
This check may as well come first to avoid performing the loop.

2020-09-09 12:44 UTC, DanNixon commented on src/modules/checkspecies/process.cpp
> +
There looks to be a fair bit of duplication here, can this easily be avoided?

2020-09-10 11:28 UTC, trisyoungs commented on src/modules/checkspecies/functions.cpp
> +    if (source.size() != ref.size())
From an efficiency perspective this is valid, but potentially hides other useful information - its possible for the number of parameters as well as their respective values to be incorrect, and this is all useful output to the user.

2020-09-10 11:48 UTC, DanNixon commented on src/modules/checkspecies/functions.cpp
> +    if (source.size() != ref.size())
But if the number of parameters and number of checked values differ there is no longer any guarantee that the correct pairs of values are being checked.

2020-09-10 13:08 UTC, trisyoungs commented on src/modules/checkspecies/process.cpp
> +
With a templated function and some STL magic, yes.

2020-09-11 08:10 UTC, rprospero reviewed
A couple of design comments, but otherwise everything looks good.

2020-09-11 08:10 UTC, rprospero commented on src/keywords/vector_intdouble.h
> +typedef std::vector<std::tuple<std::vector<int>, std::vector<double>>> IntegerDoubleVectorKeywordData;
Wouldn't we be better off with `std::vector<std::vector<std::tuple<int, double>>`?  This would ensure that there are always an equal number of integers and doubles.  Or is that no desireable?

2020-09-11 08:10 UTC, rprospero commented on src/keywords/vector_intstring.h
> +typedef std::vector<std::tuple<std::vector<int>, std::vector<std::string>>> IntegerStringVectorKeywordData;
Same comment as with vector_intdouble

2020-09-11 08:10 UTC, rprospero commented on src/keywords/vector_intstring.h
> +class IntegerStringVectorKeyword : public KeywordData<IntegerStringVectorKeywordData &>
After looking through the implementation classes, couldn't we have a single `IntegerTVector` template that takes the second type as a parameter?  The code for the two classes seems identical.  Or, if not a template, at least a base class that can get subclassed out for the parts that actually change?

2020-09-11 08:19 UTC, trisyoungs commented on src/modules/checkspecies/checkspecies.h
> +                Messenger::print("  ... parameter {} is incorrect ({:.5e} vs. {:.5e} reference, delta = {:.5e}", n + 1,
I tend to use `Messenger::error` exclusively for syntactic, programmatic, or otherwise 'hard' errors that should stop execution at that point. When testing, I prefer to think of these 'scientific' errors separately, and so just print normal information (partly for readability reasons when looking through the system test logs).

2020-09-11 08:20 UTC, trisyoungs commented on src/keywords/vector_intdouble.h
> +typedef std::vector<std::tuple<std::vector<int>, std::vector<double>>> IntegerDoubleVectorKeywordData;
The number of integers and the number of doubles (or strings) is never guaranteed to be equal, hence the v-t-v ordering.

2020-09-11 08:21 UTC, trisyoungs commented on src/keywords/vector_intstring.h
> +class IntegerStringVectorKeyword : public KeywordData<IntegerStringVectorKeywordData &>
Yes, as I mentioned in the PR text this could no doubt be templated to some degree. In the first instance where there are only two similar classes I went for simplicity, but if a third (fourth...) derivative is required in the future then certainly we should template.

2020-09-14 08:45 UTC, DanNixon approved these changes
:+1:

2020-09-15 08:35 UTC, merged