Move terms in SpeciesAtom to references
projectdissolve/dissolve pull request #378
Opened 2020-09-15 14:37 UTC by rprospero

The pointers in SpeciesAtom have been converted into references.  References were chosen over safe pointers because the actual values are contained in a `std::vector` in `Species`, so the lifetime of the vector and of the pointer would conflict.

2020-09-15 14:40 UTC, rprospero commented
As a preemptive comment, many places in here have explicit type declarations, instead of `auto`.  This is necessary since the vectors contain reference wrappers and declaring a reference to the exact type is necessary to unwrap it.

2020-09-15 15:07 UTC, trisyoungs commented on src/classes/species.cpp
> +            SpeciesAtom *partner = bond.partner(i);
```suggestion
            auto *partner = bond.partner(i);
```

2020-09-15 15:22 UTC, trisyoungs requested changes
This all looks pretty good - makes a lot of stuff look a lot neater.  I've made a handful of suggestions, but the vast majority are me adding uses of `auto` that I missed in my original sweep.

2020-09-15 15:22 UTC, trisyoungs commented on src/classes/species_intra.cpp
> +    // to derference its `this` pointer in the constructor
```suggestion
    // to dereference its `this` pointer in the constructor
```

2020-09-15 15:22 UTC, trisyoungs commented on src/classes/species_intra.cpp
> +    angles_.push_back(std::move(tmp));
My lack of knowledge on move semantics may fail me here, but can this be one-lined (i.e. `angles_.push_back(std::move(SpeciesAngle(i,j,k)))` or does `std::move` dislike objects created in-line?

2020-09-15 15:22 UTC, trisyoungs commented on src/classes/species_intra.cpp
> +        OptionalReferenceWrapper<SpeciesBond> jk = torsion.j()->hasBond(torsion.k());
```suggestion
        auto jk = torsion.j()->hasBond(torsion.k());
```

2020-09-15 15:22 UTC, trisyoungs commented on src/data/ff.cpp
> +                SpeciesAtom *j = i->bond(indexJ).partner(i);
```suggestion
                auto *j = i->bond(indexJ).partner(i);
```

2020-09-15 15:22 UTC, trisyoungs commented on src/data/ff.cpp
> +                    SpeciesAtom *k = i->bond(indexK).partner(i);
```suggestion
                    auto *k = i->bond(indexK).partner(i);
```

2020-09-15 15:22 UTC, trisyoungs commented on src/data/ff.cpp
> +                        SpeciesAtom *l = i->bond(indexL).partner(i);
```suggestion
                        auto *l = i->bond(indexL).partner(i);
```

2020-09-15 15:22 UTC, trisyoungs commented on src/neta/connection.cpp
> +                                    [j](const SpeciesBond &bond) { return bond.partner(j)->element()->Z() == ELEMENT_H; });
Nice.

2020-09-15 15:22 UTC, trisyoungs commented on src/neta/presence.cpp
> +                                    [j](const SpeciesBond &bond) { return bond.partner(j)->element()->Z() == ELEMENT_H; });
++nice

2020-09-16 08:53 UTC, rprospero commented on src/classes/species_intra.cpp
> +    angles_.push_back(std::move(tmp));
That worked just fine.

2020-09-16 10:45 UTC, trisyoungs approved these changes
This can be merged whenever you're ready.  The pipeline failure is to do with the website, and which can be ignored.

2020-09-16 12:52 UTC, merged