Code Tidy November 2019
projectdissolve/dissolve pull request #413
Opened 2020-11-02 11:41 UTC by trisyoungs

THis PR attempts to win the award for the most boring piece of work so far, and deals with:

- Removing all warnings associated with unused variables.
- Removing many warnings associated to comparison between signed and unsigned ints.
- Replaces some magic numbers with `std::optional` where appropriate.
- Fixes some initialisation order warnings, and moves to initialiser lists where appropriate.
- Removes a couple of other errors related to polymorphic class destructors and potential variable use when uninitialised.
- Sprinkles many `auto` in `for` loops.

Not all signed/unsigned int warnings are removed, since some required more fundamental changes to classes beyond the scope of this PR (e.g. `Module::nTargetConfigurations()`).

**Builds on #412 - do not merge until #412 is resolved.**

2020-11-09 09:58 UTC, DanNixon requested changes
I don't like all the `unsigned`s being thrown around here. See https://google.github.io/styleguide/cppguide.html#Integer_Types for details.

I short, integers should be signed, when iterating using indices the appropriate size type should be used (e.g. std::vector::size_type, or via decltype()).

2020-11-09 10:32 UTC, trisyoungs commented
Should have read that first! Reverted the `unsigned int` stuff.

2020-11-09 16:57 UTC, rprospero approved these changes
Some pedantic comments, but it's a supposed to be a tidy PR

2020-11-09 16:57 UTC, rprospero commented on src/math/interpolator.cpp
> +Interpolator::Interpolator(const Array<double> &x, const Array<double> &y, InterpolationScheme scheme) : x_(x), y_(y)
Good catch

2020-11-09 16:57 UTC, rprospero commented on src/math/interpolator.cpp
> +    const int nPoints = x_.nItems();
Could this be `const auto`?

2020-11-09 16:57 UTC, rprospero commented on src/modules/rdf/functions.cpp
>          // 				{
While we're cleaning up, do we want to take out all this commented code?

2020-11-09 16:57 UTC, rprospero commented on src/modules/refine/functions.cpp
> +    //     const auto idJ = typeJ->index();
Just delete these lines?

2020-11-09 16:57 UTC, rprospero commented on src/modules/sq/process.cpp
> +        //             for (auto j = i; j < unweightedsq.nAtomTypes(); ++j)
Again, should we cut these comments?

2020-11-09 18:43 UTC, trisyoungs commented on src/math/interpolator.cpp
> +Interpolator::Interpolator(const Array<double> &x, const Array<double> &y, InterpolationScheme scheme) : x_(x), y_(y)
Thanks. Shame it got there in the first place though!

2020-11-09 18:46 UTC, trisyoungs commented on src/math/interpolator.cpp
> +    const int nPoints = x_.nItems();
Yep - got reverted along with the `unsigned int`.

2020-11-09 18:47 UTC, trisyoungs commented on src/modules/rdf/functions.cpp
>          // 				{
I have been meaning to add an issue to remove all of the stuff related to this, which is an attempt to broaden intramolecular terms based on their fundamental frequency.  It was horrible in the first place, and so I don't mind losing it! I'll add an issue to that effect.

2020-11-09 18:51 UTC, trisyoungs commented on src/modules/refine/functions.cpp
> +    //     const auto idJ = typeJ->index();
Similar argument to above, but this time the whole module needs to go!

2020-11-09 18:52 UTC, trisyoungs commented on src/modules/sq/process.cpp
> +        //             for (auto j = i; j < unweightedsq.nAtomTypes(); ++j)
This I would prefer to leave in for the time being, as the very next major bit of work will immediately reinstate this section.

2020-11-09 18:57 UTC, trisyoungs commented on src/keywords/nodevalueenumoptions.h
> +          KeywordData<Venum<NodeValue, E>>(KeywordBase::NodeValueEnumOptionsData, Venum<NodeValue, E>(value, enumOptions))
Just changed the order to match that of the inheritance heirarchy - even `gcc` warned about this one...

2020-11-09 18:58 UTC, trisyoungs commented on src/expression/functions.cpp
> +    for (auto result = (int)ExpressionFunctions::NoFunction; result < ExpressionFunctions::nFunctions; ++result)
Yes, sounds sensible. Do you want to go ahead an add an issue?

2020-11-11 10:10 UTC, DanNixon approved these changes

2020-11-11 10:12 UTC, merged