Use proper containers for Array2D
projectdissolve/dissolve pull request #458
Opened 2020-11-30 15:40 UTC by rprospero

This PR moves Array2D to be on a std::vector, instead of a raw array.  Additionally, it adds standard container accessors to the Array2D API, allowing it to be used in standard algorithms.  Finally, it puts those algorithms to use across the code.

2020-12-03 10:01 UTC, trisyoungs requested changes
This is excellent. Much cleaner, shorter, and better all round. Few comments and possible bugs highlighted in the review.

2020-12-03 13:39 UTC, rprospero commented on src/templates/array2d.h
> +        std::transform(array_.begin(), array_.end(), array_.begin(), [value](auto n) { return n + value; });
I don't think `std::transform` strictly requires a reference here, since nothing has to be modified in place (that's handled by the return of the lambda).  However, you're right that, in the case where `A` is, for example, a vector of doubles, that results in us copying the vector value constantly.  Now, the compiler is *probably* smart enough to inline that, but I should just make the switch.

2020-12-03 14:33 UTC, rprospero commented on src/base/processpool.cpp
> +            return false;
Good catch.  I've talked about putting in a more generic broadcast system and part of that will have to be having a generic compile time type name printer.  In the mean time, though, still need to do everything properly.

2020-12-03 14:36 UTC, rprospero commented on src/base/processpool.cpp
>                  return false;
I'm always in favour of shorter code.

2020-12-03 14:40 UTC, rprospero commented on src/genericitems/array2d.h
>              data_.initialise(nRows, nColumns, half);
Yeah, I tried to go too tricky with that.  I'm pushing an updated version that I hope will be clearer and correct.

2020-12-03 15:05 UTC, rprospero commented on src/math/extrema.cpp
>          return 0;
No, the affirmative tests look decidely cleaner and shorter

2020-12-03 15:13 UTC, rprospero commented on src/math/gj.cpp
> +    auto array = A.linearArray();
No, the standard mandates that `auto` only creates value types and that I should have put in a reference there.

2020-12-04 13:25 UTC, rprospero commented
I believe that I have made all of the suggested changes.

2020-12-04 13:37 UTC, trisyoungs approved these changes
:+1:

2020-12-04 13:38 UTC, merged